### ISSUE TITLE
更新过后wifi打不开，提升没关联

### ISSUE THREAD

**Issue by a871516130** [retro98boy/openwrt-tn3399-v3#1]
![屏幕截图 2024-03-18 160831](https://github.com/retro98boy/openwrt-tn3399-v3/assets/28917912/cfc96b7e-bdda-4112-8f4b-c3042681081a)

**Comment by retro98boy** [comment]
不好意思，这个我暂时解决不了

更新过后打不开？以前的旧版本可以？我记得我这边一直不可用

**Comment by a871516130** [comment]
老哥，留个联系方式，我把源码发给你，我也忘了我改了什么地方，目前 23.5.0 是可以用 5g wifi，2.4 残废

**Comment by retro98boy** [comment]
> 老哥，留个联系方式，我把源码发给你，我也忘了我改了什么地方，目前 23.5.0 是可以用 5g wifi，2.4 残废

retro98boy@qq.com

**Comment by a871516130** [comment]
我记得改了这个，在23.5.0可以用

________________________________
发件人: retro98boy ***@***.***>
发送时间: 2024年3月23日 11:46
收件人: retro98boy/openwrt-tn3399-v3 ***@***.***>
抄送: a871516130 ***@***.***>; Author ***@***.***>
主题: Re: [retro98boy/openwrt-tn3399-v3] 更新过后wifi打不开，提升没关联 (Issue #1)


老哥，留个联系方式，我把源码发给你，我也忘了我改了什么地方，目前 23.5.0 是可以用 5g wifi，2.4 残废

***@***.******@***.***>

―

**Comment by retro98boy** [comment]
> ![屏幕截图 2024-03-18 160831](https://private-user-images.githubusercontent.com/28917912/313595513-cfc96b7e-bdda-4112-8f4b-c3042681081a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTQ3OTAsIm5iZiI6MTcxMTg5NDQ5MCwicGF0aCI6Ii8yODkxNzkxMi8zMTM1OTU1MTMtY2ZjOTZiN2UtYmRkYS00MTEyLThmNGItYzMwNDI2ODEwODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE0MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjY3ODM3YzAxMTQxNGQ5ZmEyNTA1ODE1MDc2N2M3ZWY2MjBlYjdhZDZmNmY0MTIzN2IwN2NjMjM3NmNiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMWSukAmoToVYWRzn76L6mJjsrL_05LPAyc9yj6gq7I)

编译的时候选上wpad就行了，23.05.3的版本已经修复

**Comment by a871516130** [comment]
感谢老哥
________________________________
发件人: retro98boy ***@***.***>
发送时间: 2024年3月31日 14:16
收件人: retro98boy/openwrt-tn3399-v3 ***@***.***>
抄送: a871516130 ***@***.***>; Author ***@***.***>
主题: Re: [retro98boy/openwrt-tn3399-v3] 更新过后wifi打不开，提升没关联 (Issue #1)


[屏幕截图 2024-03-18 160831]<https://private-user-images.githubusercontent.com/28917912/313595513-cfc96b7e-bdda-4112-8f4b-c3042681081a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTQ3OTAsIm5iZiI6MTcxMTg5NDQ5MCwicGF0aCI6Ii8yODkxNzkxMi8zMTM1OTU1MTMtY2ZjOTZiN2UtYmRkYS00MTEyLThmNGItYzMwNDI2ODEwODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE0MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjY3ODM3YzAxMTQxNGQ5ZmEyNTA1ODE1MDc2N2M3ZWY2MjBlYjdhZDZmNmY0MTIzN2IwN2NjMjM3NmNiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UMWSukAmoToVYWRzn76L6mJjsrL_05LPAyc9yj6gq7I>

编译的时候选上wpad就行了，23.05.3的版本已经修复

―
